-- CreateEnum
CREATE TYPE "FLAVOUR" AS ENUM ('BLACKFOREST', 'VANILLA', 'WHITEFOREST', 'CLASSIC_CHOCOLATE', 'BUTTERSCOTCH', 'PINEAPPLE', 'STRAWBERRY', 'BLUEBERRY', 'CHOCOVANILLA', 'CRUNCHY_BUTTERSCOTCH', 'CHOCOLATE_TRUFFLE', 'MANGO', 'HAZELNUT', 'OPERA', 'RED_VELVET', 'OREO', 'MOCHA', 'RASMALAI', 'SUGERFREE_VANILLA', 'MIX_FRUITS', 'CHOCO_BERRY', 'CHOCOLATE_OVERLOAD');

-- CreateEnum
CREATE TYPE "SHAPE" AS ENUM ('ROUND', 'SQUARE', 'RECTANGULAR', 'HEART', 'OVAL');

-- CreateEnum
CREATE TYPE "ICING_TYPE" AS ENUM ('BUTTERCREAM', 'FONDANT', 'ROYAL_ICING', 'CREAM_CHEESE', 'GANACHE');

-- CreateEnum
CREATE TYPE "ICING_COLOR" AS ENUM ('BLUE', 'PINK', 'RED', 'WHITE', 'PURPLE', 'YELLOW', 'ORANGE', 'GRAY', 'DARK_CHOCOLATE', 'BROWN', 'CREAM', 'BLACK', 'LAVENDER', 'MINT_GREEN', 'LIGHT_PINK', 'LIGHT_BLUE', 'MULTI_COLOR', 'GOLD', 'SILVER');

-- CreateEnum
CREATE TYPE "TIERS" AS ENUM ('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE');

-- CreateEnum
CREATE TYPE "HEIGHT" AS ENUM ('NORMAL', 'TALL', 'EXTRA_TALL');

-- CreateTable
CREATE TABLE "cake_details" (
    "id" UUID NOT NULL,
    "orderId" UUID NOT NULL,
    "size" VARCHAR(255) NOT NULL,
    "text" TEXT NOT NULL,
    "flavour" "FLAVOUR" NOT NULL,
    "isEggLess" BOOLEAN NOT NULL DEFAULT false,
    "isLessCream" BOOLEAN NOT NULL DEFAULT false,
    "isExtraJuicy" BOOLEAN NOT NULL DEFAULT false,
    "shape" "SHAPE" NOT NULL,
    "icingType" "ICING_TYPE" NOT NULL,
    "icingColor" "ICING_COLOR" NOT NULL,
    "tiers" "TIERS" NOT NULL,
    "height" "HEIGHT" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "cake_details_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "cake_details_orderId_key" ON "cake_details"("orderId");

-- AddForeignKey
ALTER TABLE "cake_details" ADD CONSTRAINT "cake_details_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;
